`timescale 1ns / 1ps

// -----------------------------------------------------------------------------
// Module: requantize_relu_pipelined
// Purpose: Timing-refined version of requantize_relu with one internal
//          pipeline register placed after the fixed-point multiply and before
//          rounding/saturation.
//
// Numerical contract:
//   S_acc = S_a * S_w
//   M     = S_acc / S_out
//   M ~= M_INT / 2^FRAC_BITS
//
// Stage 1:
//   acc_in -> ReLU/sign gate -> 18-bit magnitude -> 42-bit product register
//
// Stage 2:
//   product register -> rounding -> shift -> saturation -> q_out
//
// Assumptions established in Phase 6:
//   - Normal generated INT8 operands are in [-127, +127].
//   - A 3x3 single-channel convolution therefore has positive magnitude
//     bounded by 145161 after ReLU.
//   - Valid positive accumulator magnitude fits in 18 unsigned bits.
//   - M_INT is a 24-bit unsigned layer constant.
//   - FRAC_BITS is a compile-time constant in the range 0..42.
//   - Reset is synchronous and active high.
//   - q_out is combinational from the registered product. The architectural
//     activation register is external and captures q_out on the next edge.
// -----------------------------------------------------------------------------
module requantize_relu_pipelined #(
    parameter [23:0] M_INT      = 24'd1,
    parameter integer FRAC_BITS = 0
)(
    input  wire               clk,
    input  wire               rst,
    input  wire signed [31:0] acc_in,
    output reg  signed [7:0]  q_out
);

    // ReLU/sign gate. Non-positive accumulators are converted to zero before
    // multiplication, so no sign/control bit has to cross the pipeline stage.
    wire acc_positive = (~acc_in[31]) && (|acc_in);

    // Under the Phase 6 bounded-data contract, every valid positive result is
    // <= 145161 and therefore fits exactly in 18 unsigned bits.
    wire [17:0] acc_mag = acc_positive ? acc_in[17:0] : 18'd0;

    // Stage-1 combinational multiply. 18 unsigned bits x 24 unsigned bits
    // requires exactly 42 result bits.
    wire [41:0] product_next = acc_mag * M_INT;

    // Pipeline boundary selected from the measured routed critical path.
    // Keeping the full 42-bit raw product preserves exact arithmetic for the
    // subsequent rounding stage.
    reg [41:0] product_reg;

    always @(posedge clk) begin
        if (rst)
            product_reg <= 42'd0;
        else
            product_reg <= product_next;
    end

    // Stage-2 rounding and scaling. One extra bit is retained for a possible
    // carry generated by the rounding bias.
    wire [42:0] product_ext = {1'b0, product_reg};
    wire [42:0] rounded_num;
    wire [42:0] q_pre_wide;

    generate
        if (FRAC_BITS == 0) begin : gen_no_fractional_shift
            assign rounded_num = product_ext;
            assign q_pre_wide  = rounded_num;
        end else begin : gen_fractional_shift
            wire [42:0] rounding_bias;
            assign rounding_bias = (43'd1 << (FRAC_BITS - 1));
            assign rounded_num   = product_ext + rounding_bias;
            assign q_pre_wide    = rounded_num >> FRAC_BITS;
        end
    endgenerate

    // Since every non-positive input becomes product_reg == 0 in Stage 1,
    // Stage 2 only needs to distinguish normal range from saturation.
    always @(*) begin
        if (|q_pre_wide[42:7])
            q_out = 8'sd127;
        else
            q_out = $signed(q_pre_wide[7:0]);
    end

endmodule
